name = "Mimosa"
uuid = "2e41fa5d-e7f2-4070-8a6b-25ce77bfeb85"
version = "0.1.0"
authors = ["Mimosa contributors"]
repo = "https://github.com/mimosa-jl/Mimosa.jl.git"
license = "MIT"
keywords = ["motif", "bioinformatics", "PWM", "BaMM", "Julia"]
description = "Motif scanning, comparison, and statistical evaluation in Julia"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
PrecompileTools = "1.3.4"
Printf = "1.10"
Random = "1.10"
SHA = "0.7"
TOML = "1.0"
julia = "1.10"
